#!/usr/bin/env bash
# 1-create_ssh_key_pair
# This script creates an RSA key pair named 'school' with 4096 bits(long),
# protected by the passphrase 'betty'.

ssh-keygen -t rsa -b 4096 -f school -N betty
