#!/usr/bin/env bash

# Usage function
usage() {
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
}

# Check that exactly 4 arguments supplied
if [ "$#" -ne 4 ]; then
    usage
    exit 1
fi

FILE_PATH="$1"
IP="$2"
USERNAME="$3"
SSH_KEY_PATH="$4"

# Use scp to copy the file to the remote user's home directory
# StrictHostKeyChecking=no to disable strict host key checking
scp -i "$SSH_KEY_PATH" -o StrictHostKeyChecking=no "$FILE_PATH" "${USERNAME}@${IP}:~/"
