#!/usr/bin/env bash
# Script to install Nginx and configures simple page 

apt-get update -y
apt-get install -y nginx # Installing Nginx server

# Ensure root directive points to /var/www/html and index includes index.html
sed -i 's#root .*;#root /var/www/html;#g' /etc/nginx/sites-available/default
sed -i '/index /c\    index index.html index.htm index.nginx-debian.html;' /etc/nginx/sites-available/default

# Restarting using service command (no systemctl)
service nginx restart #
