#!/usr/bin/env bash
# Script to install Nginx and configures simple page 

apt-get update -y
apt-get install -y nginx # Installing Nginx server

# Write the expected content to index.html
mkdir -p /var/www/web01/html/index.html
echo "Holberton School for the win!" > /var/www/web01/html/index.html

# Restarting using service command (no systemctl)
service nginx restart #
